INSERT INTO COMPANIES(COMPANY_ID, COMPANY_NAME, TICKER_SYMBOL, SECTOR_ID) VALUES(1, 'Company 1', 'COMP1', 1);
INSERT INTO COMPANIES(COMPANY_ID, COMPANY_NAME, TICKER_SYMBOL, SECTOR_ID) VALUES(2, 'Company 2', 'COMP2', 2);
INSERT INTO COMPANIES(COMPANY_ID, COMPANY_NAME, TICKER_SYMBOL, SECTOR_ID) VALUES(3, 'Company 3', 'COMP1', 2);
