drop table ORDERS if exists;

create table ORDERS(
	ORDER_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	SYMBOL VARCHAR(20) NOT NULL,
	SIDE VARCHAR(4) NOT NULL,
	TYPE VARCHAR(10) NOT NULL,
	PRICE DOUBLE(20) DEFAULT NULL,
	VOLUME INT(20) NOT NULL,
	PLACEMENT_TIMESTAMP TIMESTAMP NOT NULL,
	TRADER_ID BIGINT(20) NOT NULL,
	STATUS VARCHAR(20) DEFAULT 'OPEN',
	PRIMARY KEY (ORDER_ID));