drop table QUOTES if exists;

CREATE TABLE QUOTES(
	QUOTE_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	BUY_ID BIGINT(20) NOT NULL,
	SELL_ID BIGINT(20) NOT NULL,
	PRICE DOUBLE(20) DEFAULT NULL,
	VOLUME INT(20) NOT NULL,
	FULFILLED_TIMESTAMP TIMESTAMP NOT NULL,
	PRIMARY KEY (QUOTE_ID),
	FOREIGN KEY (BUY_ID) REFERENCES ORDERS(ORDER_ID),
	FOREIGN KEY (SELL_ID) REFERENCES ORDERS(ORDER_ID)
);