INSERT INTO SECTORS(SECTOR_ID, SECTOR_NAME, SECTOR_DESCRIPTION) VALUES(1, 'Sector1', 'Desc for Sector 1');
INSERT INTO SECTORS(SECTOR_ID, SECTOR_NAME, SECTOR_DESCRIPTION) VALUES(2, 'Sector2', 'Desc for Sector 2');
INSERT INTO SECTORS(SECTOR_ID, SECTOR_NAME, SECTOR_DESCRIPTION) VALUES(3, 'Sector3', 'Desc for Sector 3');