drop table SECTORS if exists;

CREATE TABLE SECTORS(
	SECTOR_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	SECTOR_NAME VARCHAR(100) NOT NULL,
	SECTOR_DESCRIPTION VARCHAR(100) NOT NULL,
	PRIMARY KEY (SECTOR_ID)
);