INSERT INTO TRADERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS) VALUES('Ernest', 'Che', 'erny@gmail.com', '6593852412', 'Ang Mo Kio');
INSERT INTO TRADERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS) VALUES('Kevin', 'Koh', 'erny@gmail.com', '6591245932', 'Novena');
INSERT INTO TRADERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS) VALUES('Miri', 'Mini', 'erny@gmail.com', '6591145767', 'City Hall');
