drop table TRADERS if exists;

create table TRADERS(
	TRADER_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	FIRST_NAME VARCHAR(20) NOT NULL,
	LAST_NAME VARCHAR(20) NOT NULL,
	EMAIL VARCHAR(30) NOT NULL,
	PHONE VARCHAR(20) NOT NULL,
	ADDRESS VARCHAR(50) NOT NULL,
	PRIMARY KEY (TRADER_ID));