INSERT INTO TRADERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, USERNAME) VALUES('Ernest', 'Che', 'erny@gmail.com', '6593852412', 'Ang Mo Kio', 'ernest');
INSERT INTO TRADERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, USERNAME) VALUES('Kevin', 'Koh', 'erny@gmail.com', '6591245932', 'Novena', 'john');
INSERT INTO TRADERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, USERNAME) VALUES('Miri', 'Mini', 'erny@gmail.com', '6591145767', 'City Hall', 'admin');
