drop table USERS if exists;

create table USERS(
    USER_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(80) NOT NULL,
	ENABLED BOOLEAN DEFAULT TRUE,
	PRIMARY KEY (USERNAME)
);