INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES('ernest', 'che', TRUE);
INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES('john', 'smith', TRUE);
INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES('admin', 'admin', TRUE);
