drop table USERS if exists;

create table USERS(
	USER_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(20) NOT NULL,
	USER_ROLE VARCHAR(30) NOT NULL,
	PRIMARY KEY (USER_ID));