INSERT INTO USERS (USERNAME, PASSWORD, USER_ROLE) VALUES('john', 'smith', 'USER');
INSERT INTO USERS (USERNAME, PASSWORD, USER_ROLE) VALUES('ernest', 'che', 'USER');
INSERT INTO USERS (USERNAME, PASSWORD, USER_ROLE) VALUES('admin', 'admin', 'ADMIN');
